#! /bin/bash

echo "Path To Directory You Want: "
echo "(From Home So Backtrack If Needed)"

read getdirpath

echo "User Name: "

read username

echo "Host: "

read host

echo "Directory Name: "
echo "(Will Drop To Desktop)"

read directory

scp -r ${username}@${host}:~${getdirpath} ~/Desktop/${directory}
