#! /bin/bash

echo "Send Directory: "

read sendDirectory

echo "User Name: "

read username

echo "Host: "

read host

echo "Path to Drop: "
echo "(Leave Blank To Copy To User Home Directory)"

read path

scp -r ${sendDirectory} ${username}@${host}:~${path}
